import { ClassType } from "./classes";
import { Student } from "./students";
import { Teacher } from "./teachers";

export const studentsData: Student[] = [
  {
    id: 1,
    firstName: "Ali",
    lastName: "Valiyev",
    classId: 1,
    address: "Tashkent",
    phone: "998901234567",
    reyting: 85,
  },
  {
    id: 2,
    firstName: "Sara",
    lastName: "Khalilova",
    classId: 1,
    address: "Samarkand",
    phone: "998901234568",
    reyting: 90,
  },
  {
    id: 3,
    firstName: "Javlon",
    lastName: "Jumayev",
    classId: 1,
    address: "Bukhara",
    phone: "998901234569",
    reyting: 65,
  },
  {
    id: 4,
    firstName: "Zara",
    lastName: "Nazarova",
    classId: 1,
    address: "Andijan",
    phone: "998901234570",
    reyting: 80,
  },
  {
    id: 5,
    firstName: "Dmitriy",
    lastName: "Petrov",
    classId: 2,
    address: "Fergana",
    phone: "998901234571",
    reyting: 95,
  },
  {
    id: 6,
    firstName: "Nargiza",
    lastName: "Umarova",
    classId: 3,
    address: "Namangan",
    phone: "998901234572",
    reyting: 90,
  },
  {
    id: 7,
    firstName: "Bekzod",
    lastName: "Askarov",
    classId: 3,
    address: "Jizzakh",
    phone: "998901234573",
    reyting: 70,
  },
  {
    id: 8,
    firstName: "Shirin",
    lastName: "Raxmatova",
    classId: 3,
    address: "Nukus",
    phone: "998901234574",
    reyting: 60,
  },
  {
    id: 9,
    firstName: "Sardor",
    lastName: "Ganiev",
    classId: 3,
    address: "Gulistan",
    phone: "998901234575",
    reyting: 85,
  },
  {
    id: 10,
    firstName: "Dilorom",
    lastName: "Murodova",
    classId: 3,
    address: "Kokand",
    phone: "998901234576",
    reyting: 80,
  },
  {
    id: 11,
    firstName: "Kamron",
    lastName: "Akbarov",
    classId: 4,
    address: "Khorezm",
    phone: "998901234577",
    reyting: 88,
  },
  {
    id: 12,
    firstName: "Gulnora",
    lastName: "Jumaboyeva",
    classId: 4,
    address: "Qarshi",
    phone: "998901234578",
    reyting: 74,
  },
  {
    id: 13,
    firstName: "Olim",
    lastName: "Ibragimov",
    classId: 5,
    address: "Tashkent",
    phone: "998901234579",
    reyting: 92,
  },
  {
    id: 14,
    firstName: "Lola",
    lastName: "Saidova",
    classId: 1,
    address: "Samarkand",
    phone: "998901234580",
    reyting: 69,
  },
  {
    id: 15,
    firstName: "Sherzod",
    lastName: "Toshmatov",
    classId: 1,
    address: "Bukhara",
    phone: "998901234581",
    reyting: 78,
  },
];

export const teachersData: Teacher[] = [
  {
    id: 1,
    firstName: "Aziz",
    lastName: "Rakhimov",
    classId: 1,
    address: "Tashkent",
    email: "aziz@example.com",
    phone: "998901234601",
    subject: "Mathematics",
    reyting: 70,
  },
  {
    id: 2,
    firstName: "Gulnoza",
    lastName: "Sattarova",
    classId: 2,
    address: "Samarkand",
    email: "gulnoza@example.com",
    phone: "998901234602",
    subject: "Physics",
    reyting: 85,
  },
  {
    id: 3,
    firstName: "Jamshid",
    lastName: "Nazarov",
    classId: 3,
    address: "Bukhara",
    email: "jamshid@example.com",
    phone: "998901234603",
    subject: "Chemistry",
    reyting: 80,
  },
  {
    id: 4,
    firstName: "Dilshoda",
    lastName: "Mustafayeva",
    classId: 4,
    address: "Andijan",
    email: "dilshoda@example.com",
    phone: "998901234604",
    subject: "Biology",
    reyting: 85,
  },
  {
    id: 5,
    firstName: "Rustam",
    lastName: "Olimov",
    classId: 5,
    address: "Fergana",
    email: "rustam@example.com",
    phone: "998901234605",
    subject: "History",
    reyting: 95,
  },
];

export const classesData: ClassType[] = [
  {
    id: 1,
    name: "Class 10A",
    teacher: "Aziz Rakhimov",
  },
  {
    id: 2,
    name: "Class 10B",
    teacher: "Gulnoza Sattarova",
  },
  {
    id: 3,
    name: "Class 11A",
    teacher: "Jamshid Nazarov",
  },
  {
    id: 4,
    name: "Class 11B",
    teacher: "Dilshoda Mustafayeva",
  },
  {
    id: 5,
    name: "Class 11D",
    teacher: "Rustam Olimov",
  },
];
